# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

# To Start, Run command `docker-compose up -d --build`

services:
  barfsourcename-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=root
      - POSTGRES_DB=barfsourcenamedb
    working_dir: /tmp/scripts



