# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

# To Start, Run command `docker-compose up -d --build`

services:
  tadasourcename-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - '3308:3306'
    volumes:
      - tadasourcename-db:/var/lib/mysql
      - ./src/2.Infrastructure/Database/Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/2.Infrastructure/Database/Scripts/Dev:/tmp/scripts
    environment:
      - MYSQL_DATABASE=tadasourcenamedb
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    working_dir: /tmp/scripts

volumes:
  tadasourcename-db:
    driver: local
