name: .NET Build, Test, and Publish Nuget Package

on:
  workflow_dispatch:
  push:
    branches:
      - "main" # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - "*" # Run the workflow for all pull requests
  release:
    types:
      - published # Run the workflow when a new GitHub release is published
env:
  VERSION: 0.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore /p:Version=$VERSION

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: pack nuget packages
        run: dotnet pack --no-restore --configuration Release /p:PackageVersion=$VERSION

      # Publish the NuGet package as an artifact, so they can be used in the following jobs
      - uses: actions/upload-artifact@v3
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: output/*.nupkg

      - name: upload nuget package
        if: github.event_name == 'release'
        run: dotnet nuget push output/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
